stdio: bugfix: add preprocessor conditional analog to changes:
in file 'include/common.h' from commit 0ae74f9 to fix the following
error:

| arm-kls-linux-gnueabi-ld: common/hush.o: in function `run_shell':
| /yocto/kirkstone/build/tmp/work/imx6qdls-kls-linux-gnueabi/barebox/2025.01.0-kls1-r7.0/git/common/hush.c:1955: undefined reference to `ctrlc_handled'
| make[1]: *** [/yocto/kirkstone/build/tmp/work/imx6qdls-kls-linux-gnueabi/barebox/2025.01.0-kls1-r7.0/git/Makefile:958: .tmp_barebox1] Error 1
| make: *** [/yocto/kirkstone/build/tmp/work/imx6qdls-kls-linux-gnueabi/barebox/2025.01.0-kls1-r7.0/git/Makefile:185: sub-make] Error 2
| ERROR: oe_runmake failed
| WARNING: /yocto/kirkstone/build/tmp/work/imx6qdls-kls-linux-gnueabi/barebox/2025.01.0-kls1-r7.0/temp/run.do_compile.99429:170 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /yocto/kirkstone/build/tmp/work/imx6qdls-kls-linux-gnueabi/barebox/2025.01.0-kls1-r7.0/temp/run.do_compile.99429, line 170
| 	#2: die, /yocto/kirkstone/build/tmp/work/imx6qdls-kls-linux-gnueabi/barebox/2025.01.0-kls1-r7.0/temp/run.do_compile.99429, line 154
| 	#3: oe_runmake, /yocto/kirkstone/build/tmp/work/imx6qdls-kls-linux-gnueabi/barebox/2025.01.0-kls1-r7.0/temp/run.do_compile.99429, line 149
| 	#4: do_compile, /yocto/kirkstone/build/tmp/work/imx6qdls-kls-linux-gnueabi/barebox/2025.01.0-kls1-r7.0/temp/run.do_compile.99429, line 144
| 	#5: main, /yocto/kirkstone/build/tmp/work/imx6qdls-kls-linux-gnueabi/barebox/2025.01.0-kls1-r7.0/temp/run.do_compile.99429, line 183
ERROR: Task (/source/poky/../recipes-bsp/barebox/barebox_git.bb:do_compile) failed with exit code '1'